[WIP] Implemented most tokens
jalextowle/solidity-fix pull request #15
Opened 2019-06-05 02:14 UTC by wadeAlexC

Does not handle whitespace, some string literals, or identifiers. Added tests for all implemented tokens.

2019-06-06 22:37 UTC, wadeAlexC commented
Lexer refactor is 90% done. Immediate next steps:
1. Fix the failing test in lex_tests.rs
2. Add more tests to lex_tests
3. Clean TODOs and stray comments

Then:
4. Move the new helper functions I wrote for lex_4_25::test to a module that other tests can access
5. Start work on parser

Longer term:
6. There's still some redundancy and inefficiency that can be improved upon
7. A few unimplemented tokens (>>> and >>>=)

2019-06-10 19:26 UTC, wadeAlexC commented
Okay -- lexer now recognizes almost everything!

Added an edge case to identifier matching to handle hex literals (hex"DEADBEEF"). 2 cases I know I don't handle: escape characters in strings, and leading '.' in rational numbers.

2019-06-12 07:51 UTC, jalextowle commented on tests/parse_tests.rs
> +                        Box::new(lex_4_25::Token::BitwiseXor.to_leaf()),
I think we'll probably want to make the AST for this look like:

```
Pragma
    | Identifier("solidity")
    | Version
        | BitwiseXor
        | Version("0.4.25")
```

This looks good for now though. I'll add that to the AST issue

2019-06-12 07:52 UTC, jalextowle commented on tests/parser_integration_tests.rs
> +                        Box::new(lex_4_25::Token::BitwiseXor.to_leaf()),
Same as other comment.

2019-06-12 07:54 UTC, jalextowle commented on src/lex_4_25.rs
> +    CommentMulti,
I'm glad you added these. We need to start dealing with comments, and I think that the lexer is probably the right place for them.

2019-06-12 08:25 UTC, jalextowle requested changes
I have a couple of nits (match_period and the test comment), and after those are resolved this looks good to go. 

Overall very nice job on this!

2019-06-12 08:25 UTC, jalextowle commented on src/lex_4_25.rs
> +fn match_period(line: &Vec<char>, cur: &mut usize) -> Token {
What is the benefit of using this function over just using `Token::Dot` in the `match` statement?

On a side note, does it make sense to call periods "dots" in the Token enum? (Depending on your thoughts we can open an issue to change that. I'm not stuck on it)

2019-06-12 08:25 UTC, jalextowle commented on src/lex_4_25.rs
> +        expect_next_token(&s, cur, Token::Version(String::from("0.4.25")));
I think we should check for the semicolon token after the version

2019-06-12 08:25 UTC, jalextowle commented on tests/lex_tests.rs
> +    fn expect_next_token(s: &Vec<char>, cur: &mut usize, t: lex_4_25::Token) {
I'm a huge fan of this function! (No changes needed for this comment)

2019-06-12 08:25 UTC, jalextowle commented on src/lex_4_25.rs
> +                // (Trailing decimals are allowed, though!)
Weird! (No changes needed)

2019-06-12 08:25 UTC, jalextowle commented on src/lex_4_25.rs
> +pub fn next_token(line: &Vec<char>, cur: &mut usize) -> Token {
This is much cleaner than before. This function is very nicely done; great job on this one!

2019-06-12 08:25 UTC, jalextowle commented on src/lex_4_25.rs
> +        match self.get(idx) {
`Vec::get` is really cool. I'd like to start using this pattern in the parser if possible, where all of the errors bubble up using the Option or Result types

2019-06-12 15:55 UTC, wadeAlexC commented on src/lex_4_25.rs
> +fn match_period(line: &Vec<char>, cur: &mut usize) -> Token {
Technically `var x = .14;` is allowed, so a leading period could be a rational or part of an identifier, depending on what comes next. I was trying to figure out how to best handle this case and then I remembered that leading digits aren't allowed in identifiers. So I'll just check the next character and if it's a digit, read a rational.

I'm fine with `Dot`. `Period` is fine too. Not a big deal either way.

2019-06-12 16:03 UTC, wadeAlexC commented
Last commit addresses requested changes!

2019-06-13 16:22 UTC, jalextowle commented on src/lex_4_25.rs
> +fn match_period(line: &Vec<char>, cur: &mut usize) -> Token {
Okay that makes sense. Okay, well if you're fine with `Dot`, I'd say that we should keep it. It's sort of an easter egg I guess

2019-06-13 16:23 UTC, jalextowle approved these changes
Signed off by: Alex Towle

2019-06-13 17:25 UTC, merged